// Code generated by protoc-gen-go.
// source: grapesproto.proto
// DO NOT EDIT!

/*
Package grapes is a generated protocol buffer package.

It is generated from these files:
	grapesproto.proto

It has these top-level messages:
	NodeInfo
	ClusterInfos
*/
package core

import proto "github.com/kermitbu/grapes/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type NodeType int32

const (
	NodeType_MASTER   NodeType = 0
	NodeType_FRONTEND NodeType = 1
	NodeType_BACKEND  NodeType = 2
)

var NodeType_name = map[int32]string{
	0: "MASTER",
	1: "FRONTEND",
	2: "BACKEND",
}
var NodeType_value = map[string]int32{
	"MASTER":   0,
	"FRONTEND": 1,
	"BACKEND":  2,
}

func (x NodeType) String() string {
	return proto.EnumName(NodeType_name, int32(x))
}
func (NodeType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type NodeInfo struct {
	Ip   string   `protobuf:"bytes,1,opt,name=ip" json:"ip,omitempty"`
	Port string   `protobuf:"bytes,2,opt,name=port" json:"port,omitempty"`
	Type NodeType `protobuf:"varint,3,opt,name=type,enum=grapes.NodeType" json:"type,omitempty"`
}

func (m *NodeInfo) Reset()                    { *m = NodeInfo{} }
func (m *NodeInfo) String() string            { return proto.CompactTextString(m) }
func (*NodeInfo) ProtoMessage()               {}
func (*NodeInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *NodeInfo) GetIp() string {
	if m != nil {
		return m.Ip
	}
	return ""
}

func (m *NodeInfo) GetPort() string {
	if m != nil {
		return m.Port
	}
	return ""
}

func (m *NodeInfo) GetType() NodeType {
	if m != nil {
		return m.Type
	}
	return NodeType_MASTER
}

type ClusterInfos struct {
	Info []*NodeInfo `protobuf:"bytes,1,rep,name=info" json:"info,omitempty"`
}

func (m *ClusterInfos) Reset()                    { *m = ClusterInfos{} }
func (m *ClusterInfos) String() string            { return proto.CompactTextString(m) }
func (*ClusterInfos) ProtoMessage()               {}
func (*ClusterInfos) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ClusterInfos) GetInfo() []*NodeInfo {
	if m != nil {
		return m.Info
	}
	return nil
}

func init() {
	proto.RegisterType((*NodeInfo)(nil), "grapes.NodeInfo")
	proto.RegisterType((*ClusterInfos)(nil), "grapes.ClusterInfos")
	proto.RegisterEnum("grapes.NodeType", NodeType_name, NodeType_value)
}

func init() { proto.RegisterFile("grapesproto.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 196 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x4c, 0x2f, 0x4a, 0x2c,
	0x48, 0x2d, 0x2e, 0x28, 0xca, 0x2f, 0xc9, 0xd7, 0x03, 0x93, 0x42, 0x6c, 0x10, 0x21, 0xa5, 0x10,
	0x2e, 0x0e, 0xbf, 0xfc, 0x94, 0x54, 0xcf, 0xbc, 0xb4, 0x7c, 0x21, 0x3e, 0x2e, 0xa6, 0xcc, 0x02,
	0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0xa6, 0xcc, 0x02, 0x21, 0x21, 0x2e, 0x96, 0x82, 0xfc,
	0xa2, 0x12, 0x09, 0x26, 0xb0, 0x08, 0x98, 0x2d, 0xa4, 0xc2, 0xc5, 0x52, 0x52, 0x59, 0x90, 0x2a,
	0xc1, 0xac, 0xc0, 0xa8, 0xc1, 0x67, 0x24, 0xa0, 0x07, 0x31, 0x46, 0x0f, 0x64, 0x46, 0x48, 0x65,
	0x41, 0x6a, 0x10, 0x58, 0x56, 0xc9, 0x84, 0x8b, 0xc7, 0x39, 0xa7, 0xb4, 0xb8, 0x24, 0xb5, 0x08,
	0x64, 0x70, 0x31, 0x48, 0x57, 0x66, 0x5e, 0x5a, 0xbe, 0x04, 0xa3, 0x02, 0xb3, 0x06, 0x37, 0xaa,
	0x2e, 0x90, 0x82, 0x20, 0xb0, 0xac, 0x96, 0x21, 0xc4, 0x2d, 0x20, 0x73, 0x84, 0xb8, 0xb8, 0xd8,
	0x7c, 0x1d, 0x83, 0x43, 0x5c, 0x83, 0x04, 0x18, 0x84, 0x78, 0xb8, 0x38, 0xdc, 0x82, 0xfc, 0xfd,
	0x42, 0x5c, 0xfd, 0x5c, 0x04, 0x18, 0x85, 0xb8, 0xb9, 0xd8, 0x9d, 0x1c, 0x9d, 0xbd, 0x41, 0x1c,
	0xa6, 0x24, 0x36, 0xb0, 0x6f, 0x8c, 0x01, 0x01, 0x00, 0x00, 0xff, 0xff, 0xb4, 0x6a, 0xf8, 0x32,
	0xe2, 0x00, 0x00, 0x00,
}
